[tool.black]
line-length = 100
target-version = ['py311']

[tool.ruff]
line-length = 100
target-version = "py311"
select = [
  "E", "F", "I",
]
ignore = []
exclude = [
  ".venv",
  "demo_web",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

