[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "doc-ai-project"
version = "0.1.0"
description = "Document classification and extraction service"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "Apache-2.0"}
authors = [{name = "Your Name", email = "you@example.com"}]
dependencies = []

[project.urls]
Homepage = "https://example.com"
Repository = "https://example.com/repo"

[tool.setuptools]
packages = ["document_processing", "service", "sdk"]
[tool.black]
line-length = 100
target-version = ['py311']

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [
  ".venv",
  "demo_web",
]

[tool.ruff.lint]
select = [
  "E", "F", "I",
]
ignore = []

[tool.pytest.ini_options]
testpaths = ["tests"]

