invoice:
  description: "Invoice document"
  instructions: |
    Extract the following fields from the invoice and return as JSON:
    {
      "invoice_number": "Invoice number or ID",
      "invoice_date": "Invoice date (MM/DD/YYYY format)", 
      "vendor_name": "Company or person issuing the invoice",
      "customer_name": "Customer or company being billed",
      "total_amount": "Total amount due (number only, no currency symbol)",
      "currency": "Currency symbol (e.g., USD, $)"
    }

receipt:
  description: "Retail or service receipt" 
  instructions: |
    Extract the following fields from the receipt and return as JSON:
    {
      "transaction_id": "Receipt number or transaction ID",
      "purchase_date": "Date of purchase (MM/DD/YYYY format)",
      "merchant_name": "Name of the store or business", 
      "total_paid": "Total amount paid (number only, no currency symbol)",
      "payment_method": "Payment method (cash, credit, debit, etc.)"
    }

load_sheet:
  description: "Shipping/freight load sheet"
  instructions: |
    Extract the following fields from the load sheet and return as JSON:
    {
      "load_number": "Load or shipment number",
      "pickup_location": "Pickup address or location",
      "dropoff_location": "Delivery address or location", 
      "pickup_date": "Pickup date (MM/DD/YYYY format)",
      "dropoff_date": "Delivery date (MM/DD/YYYY format)",
      "carrier_name": "Shipping carrier or company name",
      "total_weight_lbs": "Total weight in pounds (number only)"
    }