name: Pre-commit Checks

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      if: ${{ hashFiles('.pre-commit-config.yaml') != '' }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pre-commit
    
    - name: Run pre-commit hooks
      if: ${{ hashFiles('.pre-commit-config.yaml') != '' }}
      run: |
        pre-commit install
        pre-commit run --all-files

    - name: No pre-commit config found; skipping
      if: ${{ hashFiles('.pre-commit-config.yaml') == '' }}
      run: echo "No .pre-commit-config.yaml found. Skipping pre-commit checks."
