name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build twine
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        OPENAI_API_KEY: sk-test-key-for-ci
        PYTHONPATH: .
      run: |
        pip install pytest
        pytest tests/
    
    - name: Build package
      run: |
        python -m build
    
    - name: Build Docker image
      run: |
        docker build -t document-ai-framework:${{ github.ref_name }} .
        docker tag document-ai-framework:${{ github.ref_name }} document-ai-framework:latest
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Document AI Framework ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          ## Changes in ${{ github.ref_name }}
          
          This release includes the latest improvements to the Document AI Framework.
          
          ### Installation
          ```bash
          pip install -r requirements.txt
          ```
          
          ### Docker
          ```bash
          docker run -p 8080:8080 -e OPENAI_API_KEY=your-key document-ai-framework:${{ github.ref_name }}
          ```
